---
openvas_apt_packages:
  openvas_all_pkgs:
    - autoconf
    - bison
    - build-essential
    - cmake
    - devscripts
    - doxygen
    - dpatch
    - heimdal-dev
    - heimdal-multidev
    - libassuan-dev
    - libffi-dev
    - libglib2.0-dev
    - libgmp3-dev
    - libgmp-dev
    - libgnutls-dev
    - libgpgme11-dev
    - libhiredis-dev
    - libksba-dev
    - libldap2-dev
    - libmicrohttpd-dev
    - libopenvas2
    - libpcap-dev
    - libpcre3-dev
    - libpopt-dev
    - libpth-dev
    - libsnmp-dev
    - libsqlite3-dev
    - libssh2-1-dev
    - libssh-dev
    - libwrap0-dev
    - libxml2-dev
    - libxslt1-dev
    - mingw32
    - nmap
    - pkg-config
    - python-dev
    - quilt
    - redis-server
    - sqlfairy
    - sqlite3
    - uuid-dev
    - python-setuptools
    - wamerican
    - xmltoman
    - xsltproc

openvas_src_path: "/usr/local/src"

openvas_src_packages:
  openvas_pkgs:
  - { name: "openvas-smb",                  url: "http://wald.intevation.org/frs/download.php/1975/openvas-smb-1.0.1.tar.gz" }
  - { name: "openvas_library",              url: "http://wald.intevation.org/frs/download.php/2291/openvas-libraries-8.0.7.tar.gz" }
  - { name: "openvas_scanner",              url: "http://wald.intevation.org/frs/download.php/2266/openvas-scanner-5.0.5.tar.gz" }
  - { name: "openvas_manager",              url: "http://wald.intevation.org/frs/download.php/2295/openvas-manager-6.0.8.tar.gz" }
  - { name: "openvas-cli",                  url: "http://wald.intevation.org/frs/download.php/2332/openvas-cli-1.4.4.tar.gz" }
  - { name: "greenbone-security-assistant", url: "http://wald.intevation.org/frs/download.php/2299/greenbone-security-assistant-6.0.10.tar.gz" }
  ospd_pkgs:
  - { name: "ospd",        url: "http://wald.intevation.org/frs/download.php/1999/ospd-1.0.0.tar.gz" }
  - { name: "ospd-ancor",  url: "http://wald.intevation.org/frs/download.php/2005/ospd-ancor-1.0.0.tar.gz" }
  - { name: "ospd-ovaldi", url: "http://wald.intevation.org/frs/download.php/2003/ospd-ovaldi-1.0.0.tar.gz" }
  - { name: "ospd-w3af",   url: "http://wald.intevation.org/frs/download.php/2004/ospd-w3af-1.0.0.tar.gz" }

openvas_iana_datafile:   "/tmp/openvas_iana_datafile.xml"
openvas_iana_datasource: "http://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xml"

openvas_host_address: "0.0.0.0"

openvas_admin_user:     "admin"
openvas_admin_password: "admin"

openvas_targets:
  - { address: "127.0.0.1" }
